---
name: main

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', 'pypy3']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: setup
        run: ./setup.sh
      - name: install
        run: pip install .
      - name: test
        run: python -m pytest

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
      - name: Deploy acestream-service
        env:
          ACESTREAM_SERVICE_TOKEN: ${{ secrets.ACESTREAM_SERVICE_TOKEN }}
          ENDPOINT: "vstavrinov/acestream-service/actions/workflows/main.yml"
        run: |
          curl -s -X POST                                        \
              -H "Accept: application/vnd.github.v3+json"        \
              -H "Authorization: token $ACESTREAM_SERVICE_TOKEN" \
              -d '{"ref": "master"}'                             \
              https://api.github.com/repos/$ENDPOINT/dispatches
      - name: Start SSH via Ngrok
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          # After sign up on the https://ngrok.com/
          # You can find this token here: https://dashboard.ngrok.com/get-started/setup
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

          # This password you will use when authorizing via SSH
          USER_PASS: ${{ secrets.USER_PASS }}
      - name: Don't kill instace
        if: ${{ failure() }}
        run: sleep 1h  # Prevent to killing instance after failure
